name: RSS Feed Update

on:
  schedule:
    - cron: "30 */4 * * *"
  workflow_dispatch:

jobs:
  update_rss_feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml
      - name: Run the script
        run: python RSS_Scraper.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f docs/index.xml  # Modificat pentru a include fișierul din directorul 'docs'
          TIMESTAMP=$(date -u +"%d.%m.%Y %H:%M UTC")
          git commit -m "Update RSS Feed - $TIMESTAMP" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
